### ISSUE TITLE
expose operations in user search.yaml

### ISSUE THREAD

**Issue by schmidje** [albumentations-team/autoalbument#15]
Hi,

Is there a way to expose the choice of operations used by the FAA search using the yaml file? I tried to put my operations in the policy_model section as seen in other yaml file but this is not allowed.

The reason I want to do that is to remove some operations that in my use case make little sense.

Thanks.

**Comment by creafz** [comment]
Hey @schmidje 

You should be able to select operations by setting and modifying the `policy_model.operations` list in `search.yaml`.

Here is an [example `search.yaml` for CIFAR10](https://gist.github.com/creafz/41f5c9021623bd3c15b35c50aa93992d#file-search-yaml-L50) that uses all available operations (lines 50-68). You can remove unneeded operations from it.

**Comment by schmidje** [comment]
@creafz 

Thanks but unfortunately I already tried it as follows:

```
policy_model: 
  num_sub_policies: 50
  num_chunks: 8
  operation_count: 4
  operations:
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.RandomBrightness
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.RandomContrast
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.Solarize
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.HorizontalFlip
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftX
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftY
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.Scale
```

And I get the following error:

```
Error merging =search
Key 'operations' not in 'PolicyModelConfig'
        full_key: policy_model.operations
        reference_type=PolicyModelConfig
        object_type=PolicyModelConfig
```

Using  specifies that the Exception `ConfigCompositionException` is triggered in function  `_merge_config` of file config_loader_impl.py.

My autoalbument version is 0.3.0 installed via pypi channel, is it maybe too old?
